apiVersion: http.crossplane.io/v1alpha2
kind: Request
metadata:
  name: generate-api-key
spec:
  forProvider:
    headers:
      Content-Type:
        - application/json
      Authorization:
        - Bearer {{ litellm-auth-token:default:token }}
    payload:
      baseUrl: "http://your-litellm-proxy-url:8000"
      body: |
        {
          "duration": "30d",
          "key_alias": "sample-key",
          "models": ["gpt-3.5-turbo", "gpt-4"],
          "max_budget": 100.0,
          "budget_duration": "30d",
          "metadata": {
            "team": "core-infra",
            "app": "sample-app",
            "email": "user@example.com"
          },
          "permissions": {
            "allow_pii_controls": true
          }
        }
    mappings:
      - action: Create
        method: POST
        body: |
          {
            duration: .payload.body.duration,
            key_alias: .payload.body.key_alias,
            models: .payload.body.models,
            max_budget: .payload.body.max_budget,
            budget_duration: .payload.body.budget_duration,
            metadata: .payload.body.metadata,
            permissions: .payload.body.permissions
          }
        url: .payload.baseUrl + "/key/generate"
      - action: Observe
        method: GET
        url: .payload.baseUrl + "/key/info?key=" + .response.body.key
      - action: Delete
        method: DELETE
        url: .payload.baseUrl + "/key/delete?key=" + .response.body.key
  providerConfigRef:
    name: http-conf